# Move all the installs to one line and remove apt/lists
FROM ubuntu:14.04

RUN apt-get -qq update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget nginx-full apache2-utils && \
    rm -rf /var/lib/apt/lists/*
