# Cram everything into one line including extra cleaning
FROM ubuntu:14.04

RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y wget nginx-full apache2-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
