# Extra checkpoint that deletes apt/lists
FROM ubuntu:14.04

RUN apt-get -qq update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nginx-full
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apache2-utils
# https://intercityup.com/blog/downsizing-docker-containers/
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
