#!/bin/bash
#
#

set -e

_install() {
    local pkg=$1 ver=$2 afterhook=$3

    cd /tmp

    # Download the snapshot
    wget -q https://github.com/thumbor/$pkg/archive/${ver}.zip && \
        unzip ${ver}.zip >/dev/null && rm -f ${ver}.zip

    cd "$pkg-${ver}"

    if [ -e /setup/patches/"${pkg}" ]; then
        for p in /setup/patches/"${pkg}"/*.patch; do
            patch -p1 < "${p}"
        done
    fi

    python setup.py install

    if [ -n "$afterhook" ]; then
        $afterhook
    fi

    cd /
    rm -rf "/tmp/$pkg-${ver}"
}

_install_thumbor() {
    cp -f debian/thumbor.conf /etc/thumbor.conf
}

_install thumbor $THUMBOR_VERSION _install_thumbor
_install opencv-engine $OPENCV_ENGINE_VERSION
